name = "MaterialModelsBase"
uuid = "af893363-701d-44dc-8b1e-d9a2c129bfc9"
authors = ["Knut Andreas Meyer and contributors"]
version = "0.2.3"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
MaterialModelsTesting = "882b014b-b96c-4115-8629-e17fb35110d2"

[sources]
MaterialModelsTesting = {url = "https://github.com/KnutAM/MaterialModelsTesting.jl"}

[targets]
test = ["Test", "FiniteDiff", "MaterialModelsTesting"]
